config/routes.rb
Quiz::Application.routes.draw do
  root to: "Static#home"

  get "static/about_us"

  resources :schools do
    post "/answer", to: "schools#check_answer"
end

end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :take_quizzes
  attr_accessible :left_operand, :operator, :right_operand, :title
  attr_accessor :result

  validates :left_operand, :right_operand, presence: {message: "you forgot yo stuff bro"}, 
  inclusion: { in: 1..9999999999999999999, :message => "requires an integer"}  

  def result
    a = self.left_operand
    b = self.right_operand
    x = self.operator
    a.send(x, b.to_f)
  end



end

app/models/take_quiz.rb
class TakeQuiz < ActiveRecord::Base
  belongs_to :school
  attr_accessible :answer

  # validates :answer, inclusion: {in: @school.calculate_answer(params[take_quiz])}

  validates :answer, presence: {message: "you forgot yo stuff bro"}, 
  inclusion: { in: 1..9999999999999999999, :message => "requires an integer"}

  # after_validation :validate_answer

#   def validate_answer
#     if answer != School.find(self.school_id).result
#       errors.add(:answer, "Try Again")
#     end
#   end

#   def verify_answer
#     if self.answer
#     validates :answer, inclusion: {School.caculate_answer}
#     end
#   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])
    @TakeQuiz = @school.take_quizzes.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end


  def check_answer
    @school = School.find(params[:school_id])
    @take_quiz = @school.take_quizzes.new(params[:take_quiz])
     unless @school.result.to_f == @take_quiz.answer.to_f
        return redirect_to school_path(params[:school_id]), notice: "Not the correct answer, try again"
     end

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'Your answer was correct. Hooray!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_navigation.html.erb
<div class="container">  
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">M&M productions</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "About Us", static_about_us_path %></li>
          <li><%= link_to "Create Quiz", new_school_path %></li>
          <li><%= link_to "Show Quizzes", schools_path %></li>
          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul> -->
        <!--   </li> -->
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <!-- <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button> -->
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Sign in</a></li>
          <li><a href="#">Sign up</a></li>
          <li class="dropdown">
           <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class:'container'>
<%= render "layouts/navigation" %>
<%= yield %>
</div>

</body>
</html>

app/views/schools/_answer.html.erb
<%= form_for(@TakeQuiz, url: school_answer_path(@school), method: :post) do |f| %>
  <% if @TakeQuiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@TakeQuiz.errors.count, "error") %> prohibited this TakeQuiz from being saved:</h2>

      <ul>
      <% @TakeQuiz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.number_field :answer, :type => 'float', class: "form-control"%>
  </div>
  
  <%= @school.result %>

  <div class="actions">
    <%= f.submit "Submit Answer", class: "btn btn-success" %>
  </div>

<% end %>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :left_operand %><br />
    <%= f.number_field :left_operand, :type => 'float', class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :operator %><br />
    <%= f.select :operator, options_for_select([["+", "+"], ["-", "-"], ["x", "*"], ["/", "/"]]), class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :right_operand %><br />
    <%= f.number_field :right_operand, :type => 'float', class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Create Quiz", class: 'btn-success' %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<body class="index_img">  
  <h1 class="index_page_title">Available Math Quizzes</h1>
    <div class="container">
    <table class= 'table-hover table-bordered table-striped table-responsive table-condensed' class='table table-nonfluid'>
      <tr class="success">
        <div class="row">
          <th class="col-sm-6">Title</th>
          <th class="col-sm-1">Left operand</th>
          <th class="col-sm-1">Operator</th>
          <th class="col-sm-1">Right operand</th>
          <th class="col-sm-1">Actions</th>
      </tr>

      <% @schools.each do |school| %>
      <tr>
          <td><%= link_to school.title, school %></td>
          <td><%= school.left_operand %></td>
          <td><%= school.operator %></td>
          <td><%= school.right_operand %></td>
          <td class='center_table'> 
            <div class="btn-group btn-group-xs">
              <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_school_path(school), class: 'btn btn-info' %>
              <%= link_to school, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do%>
                <span class='glyphicon glyphicon-trash'></span>
                <% end %>
            </div>
         </td>
      </tr>
      <% end %>
    </table>

    <br />

    <%= link_to 'New Quiz', new_school_path %>
  </div>
</body>

app/views/schools/new.html.erb
<h1>New Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @school.title %>
</p>

<p>
  <b>Left operand:</b>
  <%= @school.left_operand %>
</p>

<p>
  <b>Operator:</b>
  <%= @school.operator %>
</p>

<p>
  <b>Right operand:</b>
  <%= @school.right_operand %>
</p>

<h2>WHAT IS YOUR ANSWER</h2>
<%= render "schools/answer" %>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>